// Oject contain data for scene
const Scene = {
  outsideOne: {
    title: "Nhà trưng bày chính",
    image: "/images/BaotangLD1.jpg",
    pitch: 17,
    yaw: 5,
    hotSpots: {
      mapTour: {
        type: "custom",
        text: "Sơ đồ tham quan bảo tàng",
        panel: "/public/images/so-do-tham-quan.jpg",
        tooltip: "This is a tooltip",
        pitch: -1,
        yaw: -41,
        cssClass: "hotSpotElementImg",
      },
      nextScene: {
        type: "custom",
        pitch: 9.8,
        yaw: 4.1,
        cssClass: "moveScene",
        scene: "insideOne",
        // SceneID: 0
      },
      nextTour: {
        type: "custom",
        pitch: 0.2,
        text: "Dạo quanh khuôn viên",
        yaw: -125,
        cssClass: "moveScene",
        scene: "outsideTwo",
      },
      oneTour: {
        type: "custom",
        pitch: 4,
        text: "Chùa Linh Ẩn",
        yaw: -70,
        cssClass: "moveScene",
        scene: "LinhAnTour",
      },
      twoTour: {
        type: "custom",
        pitch: -3,
        text: "Nhin từ trên cao",
        yaw: 127,
        cssClass: "moveScene",
        scene: "aroundTour",
      },
      threeTour: {
        type: "custom",
        pitch: -1,
        text: "Khuôn viên chùa Linh Ẩn",
        yaw: 89,
        cssClass: "moveScene",
        scene: "LinhAnTour_01",
      },
    },
  },
  outsideTwo: {
    title: "Khuôn viên xung quanh bảo tàng",
    image: "/images/BaotangLD-outside.jpg",
    pitch: 17,
    yaw: 5,
    hotSpots: {
      outSide: {
        type: "info",
        image: "/images/so-do-tham-quan.jpg",
        text: "Nơi diễn ra các hoạt động trò chơi dân gian",
        pitch: -0.8,
        yaw: -111,
        cssClass: "hotSpotElementImg",
      },
      videoHotspot: {
        type: "custom",
        pitch: 0,
        yaw: 0,
        video: "/images/videoplayback1.mp4",
        cssClass: "videoHotspot",
      },
      nextScene: {
        type: "custom",
        pitch: -11,
        yaw: 158,
        cssClass: "moveScene",
        scene: "insideOne",
      },
      nextSceneInMap: {
        type: "custom",
        pitch: -11,
        yaw: 158,
        cssClass: "hotspot-map",
        scene: "LinhAnTour",
      },
    },
  },
  insideOne: {
    title: "Bên trong nhà trưng bày",
    image: "/images/BaotangLD10.jpg",
    pitch: 10,
    yaw: 180,
    hotSpots: {
      typeWrite: {
        type: "custom",
        pitch: -18,
        yaw: 87,
        text: "Máy đánh chữ cổ",
        nameModel: "typeWrite",
        cssClass: "hotSpotCustom",
      },
      model2: {
        type: "custom",
        pitch: -31,
        yaw: 11,
        nameModel: "batavialand",
        cssClass: "hotSpotCustom",
      },
      machineGun: {
        type: "custom",
        pitch: -7.5,
        yaw: 122,
        nameModel: "buddha_wood",
        cssClass: "hotSpotCustom",
      },
      model3: {
        type: "custom",
        pitch: -28,
        yaw: 32,
        nameModel: "roman_pottery",
        cssClass: "hotSpotCustom",
      },
      model4: {
        type: "custom",
        pitch: -6,
        yaw: 103,
        nameModel: "radio1950s",
        cssClass: "hotSpotCustom",
      },
      model5: {
        type: "custom",
        pitch: -22,
        yaw: -8,
        nameModel: "iphone_01",
        cssClass: "hotSpotCustom",
      },
      model6: {
        type: "custom",
        pitch: -12,
        yaw: 93,
        nameModel: "binh_su",
        cssClass: "hotSpotCustom",
      },
      model7: {
        type: "custom",
        pitch: -23,
        yaw: 63,
        nameModel: "stamp",
        cssClass: "hotSpotCustom",
      },

      outSide: {
        type: "custom",
        pitch: -49,
        yaw: -162,
        cssClass: "moveScene",
        scene: "outsideOne",
      },
    },
  },
  aroundTour: {
    title: "Nhin từ trên cao",
    image: "/images/panos/img1.jpg",
    pitch: 17,
    yaw: 5,
    hotSpots: {
      outSide: {
        type: "info",
        image: "/images/so-do-tham-quan.jpg",
        text: "Nơi diễn ra các hoạt động trò chơi dân gian",
        pitch: -0.8,
        yaw: -111,
        cssClass: "hotSpotElementImg",
      },
    },
  },
  LinhAnTour: {
    title: "Nhin từ trên cao",
    image: "/images/panos/img2.jpg",
    pitch: 17,
    yaw: 5,
    hotSpots: {
      outSide: {
        type: "info",
        image: "/images/so-do-tham-quan.jpg",
        text: "Nơi diễn ra các hoạt động trò chơi dân gian",
        pitch: -0.8,
        yaw: -111,
        cssClass: "hotSpotElementImg",
      },
    },
  },
  LinhAnTour_01: {
    title: "Nhin từ trên cao",
    image: "/images/panos/img7.jpg",
    pitch: 17,
    yaw: 5,
    hotSpots: {
      outSide: {
        type: "info",
        image: "/images/so-do-tham-quan.jpg",
        text: "Nơi diễn ra các hoạt động trò chơi dân gian",
        pitch: -0.8,
        yaw: -111,
        cssClass: "hotSpotElementImg",
      },
    },
  },
};

export default Scene;
